### ISSUE TITLE
Please kindly add these extra characters to the panel

### ISSUE THREAD

**Issue by dujididoya** [opt-pan/penpa-edit#3]
To incoporate Xiangqi (alongside Chess and Shogi), please add these Kanji to the panel:
シャンチーを組み込むには（チェスと将棋とともに）、これらの漢字をパネルに追加してください。

帥俥傌炮仕相兵
將車馬砲士象卒

Much appreciated!
大変感謝いたします！

**Comment by opt-pan** [comment]
I added that characters. 傌 is not used in Japan, so the font is different from others. 
Sorry for the late response.

**Comment by dujididoya** [comment]
Thank you so much for the addition of Xiangqi characters! They are worth the half-year wait. :-P

The font is good enough, the interface is working fine 100%. Nice job!

However I have a separate request (don't want to create a new issue):

Could you please add the "goats" and "wolves" symbols for the Nikoli puzzle type "Goats and Wolves" (ヤギとオオカミ). At the moment you have other symbols (like tents and trees) but oddly enough you haven't added these 2 symbols, despite the popularity of the "Goats and Wolves" puzzles.

I know we can create these puzzles using pzv.jp or puzz.link, but it would be very handy to have them on penpa-edit so we can create variant puzzles with other rules.

Thanks a million times!

**Comment by opt-pan** [comment]
On the 'Tents and trees' puzzle, it's not so hard to prepare symbols because they are made from simple shapes, but on the 'Goats and Wolves' puzzles, the illustration must be prepared as the png file.
How about using 〇 and ▽ (paramesis puzzle blog style), 〇 and □( Cross+A style), or A and B(24HPC2019 and so on style)?

**Comment by dujididoya** [comment]
Thank you very much for the reply. Understanding the difficulty, I think I can make do without the goats and wolves symbols (I had a need for them previously but found a way to work around them.

Also very nice about the new English version, even though I've been so used to the Japanese version for so long (obviously I'm mainly an English-based user who can just understand a tiny little amount of the Japanese language ;-P).

I will close this issue now. Keep up the great work!
