### ISSUE TITLE
Selective Modes while Sharing URL for Solving

### ISSUE THREAD

**Issue by swaroopg92** [opt-pan/penpa-edit#5]
Hi opt-pan,

Firstly, Thank you very much for such a wonderful tool. It's been of great help to me.
I have forked your repository (From the English Translated rjrudman fork) and have been making some small changes on my own to suit my needs.
But I am no expert in the Javascript.

Is there a way when we share the URL for solving, to select only certain modes to appear based on user selection. It's confusing for the solver to have so many options. For e.g. If I share Sudoku, I want the default mode to be Number and only that to be visible and then maybe only Middle, Side, Corner sub-modes. Another example If I share Tapa, only shading mode should appear, and so on.
Is it possible and if yes can you please implement that feature or guide me on how can I do that?

Appreciate your help.

Thank you very much,
Swaroop

**Comment by swaroopg92** [comment]
@opt-pan - Hi, Can you please provide your email id or a way to contact you privately, I have a very important thing to discuss. Thank you. or alternatively if you don't want to reveal here, you can send an email to (swaroop.guggilam@gmail.com)
Thank you.

**Comment by opt-pan** [comment]
I added the feature of mode-conservation. When you export the link for solving puzzles, the selected state of the button is inherited. If you have another good idea, please let me know.
Also, this tool now supports English. It works in English when you open with a browser other than Japanese. (You can switch between Japanese and English at any time.)
Please let me know if you have any problems.

**Comment by swaroopg92** [comment]
Thank you very much. That will be definitely helpful. Will check it out.

**Comment by swaroopg92** [comment]
I have replied to you in the email. Thanks. Closing this issue.
