### ISSUE TITLE
Not working on Ipad

### ISSUE THREAD

**Issue by swaroopg92** [opt-pan/penpa-edit#6]
On Ipad -> Safari Browser -> Loaded the Penpa -> Touching the screen-> it is scrolling the page and no impact on the canvas.
Tried on iPadOS 13.6

I tried to fix using a few different options of preventDefault(), and other suggested things on the internet but didn't work.

This issue is something to do with iOS versions > 11.3 and Safari combination may be.

**Comment by opt-pan** [comment]
Having recently finally gotten a Mac development environment, I've figured out what's probably causing the problem and fixed it.

For Developers
The cause is maybe the addEventListener trigger, which uses the "mouse event" on the PC and the "touch event" on the iphone. What I misunderstood was that the "mouse event" was used on the ipad.

**Comment by dujididoya** [comment]
Well, just so you guys know, Apple has recently (a few months ago) decided to add the mouse usage on iPads (with cursors etc) after a whole 10 years of ignoring millions of user requests! You still need to use a bluetooth mouse on the newer models, so not many would do it (I'm guess <20%) but it's still a great thing. So opt-pan san you might want to keep some of the mouse features on penpa-edit for iPads/iPhones as they can be useful for some (I personally use an iPad and love to use my bluetooth mouse/keyboard to solve/design puzzles). ;-P

**Comment by swaroopg92** [comment]
@opt-pan THanks. It now works on Ipad. Awesome. Will take a look at the changes.
If you get time, please do take a look at the two emails I sent you. Thank you.

**Comment by swaroopguggilam** [comment]
@opt-pan - After the latest update of yours, looks like there are some bugs/issues on using it on laptop. If you switch between modes (Surface to Line to Number to Line), it doesn't update the submodes and style menus properly (photo 2). Also the L-Grey in surface mode is displayed weirdly (photo 1). Please do take a look when you get time. I am attaching some photos below to clarify.

![bug1](https://user-images.githubusercontent.com/39744930/92131156-9d3b1a00-edd3-11ea-9c11-22723158b9b7.JPG)
![bug2](https://user-images.githubusercontent.com/39744930/92131155-9ca28380-edd3-11ea-8ee8-a759790a87e9.JPG)

**Comment by swaroopg92** [comment]
@opt-pan  - After the latest update of yours, looks like there are some bugs/issues on using it on laptop. If you switch between modes (Surface to Line to Number to Line), it doesn't update the submodes and style menus properly (photo 2). Also the L-Grey in surface mode is displayed weirdly (photo 1). Please do take a look when you get time. I am attaching some photos below to clarify.

![bug1](https://user-images.githubusercontent.com/19638035/92131533-1cc8e900-edd4-11ea-9439-b807720503e7.JPG)
![bug2](https://user-images.githubusercontent.com/19638035/92131534-1d617f80-edd4-11ea-8de9-0d10a89a92ec.JPG)

**Comment by opt-pan** [comment]
I fixed a problem with L.Gray sticking out. Font size may vary slightly depending on the environment...

I could not reproduce the problem of switching sub-modes. Could you try super reload (Ctrl + F5, depending on the browser) or private browsing mode?

**Comment by swaroopg92** [comment]
Thanks for your quick response.
Yes, I did super reload, pressed Ctrl+F5 multiple times. I use google chrome. 
But surprisingly it's fine in the Private mode. Maybe Ctrl+F5 is not doing effective refresh, might have to manually clear the cache.
Thanks. Closing this issue.
