### ISSUE TITLE
Possibility to raise the maximum size limits

### ISSUE THREAD

**Issue by dujididoya** [opt-pan/penpa-edit#8]
I've been wanting to bring up this issue for months but not sure if opt-pan san is too busy so just stayed silent.

The problem is when I create puzzles/grids using penpa-edit very frequently I find the size limits just one or two smaller than my desired size. I will give some examples:

- for Square, I often want to make boards of 32x32, but the upper limit is 30
- for Cube, I often want to make 16x16x16 cubes, but the upper limit is 15
- for Hexagon, I often want to make grids with side length 12, but the upper limit is 10

Don't know why you chose these particular limits (memory buffer sizes?), but it would be greatly appreciated if you can somehow raise these limits (Square -> 32, Cube -> 16, Hexagon -> 12) if they don't cause too much troubles to be increased.

Also, thanks so much for the recent upgrade of the interface (e.g. the new deep blue color is lovely!). Keep up the great work! :-D

**Comment by swaroopg92** [comment]
The size limit is to do with the URL length generation. After a certain amount of elements on the canvas, the URL becomes longer than the limit and then you cant share with others, it will give you error "HTTP 414 URI Too Long ". I did increase the upper limit at least for Square on my fork, but I am looking into this issue and haven't found any proper solution yet.
If your grid doesn't have too many elements then it should work fine.
Also, it only affects sharing, you can still create a screenshot, and generate a URL and save it locally. If you clone the repository, then the link will always work on your local computer. The URI too long error is something to do with GitHub server limitation.

**Comment by dujididoya** [comment]
> The size limit is to do with the URL length generation. After a certain amount of elements on the canvas, the URL becomes longer than the limit and then you cant share with others, it will give you error "HTTP 414 URI Too Long ". I did increase the upper limit at least for Square on my fork, but I am looking into this issue and haven't found any proper solution yet.
> If your grid doesn't have too many elements then it should work fine.
> Also, it only affects sharing, you can still create a screenshot, and generate a URL and save it locally. If you clone the repository, then the link will always work on your local computer. The URI too long error is something to do with GitHub server limitation.

Thanks so much for your reply, swaroopg92. I suspected it'd be something like this, that's why I'm not asking for a huge increase, just 30->32 for square, 15->16 for cube, 10->12 for hexagon (well the last one is definitely optional). It's just that when creating puzzles I found that multiples of 4 & 8 (i.e. 32 & 16 here) occur much more likely than say 30 or 15.

I never share the links much (they're too long to use for the forums I visit, which has a high level of moderation on links and such), instead I use this lovely web-app to create and save great images for sharing. I only save the URLs as bookmarks on my browser, so the length will never be an issue for me. Also what I create typically has lots of elements so the lengths are always huge (over 1000 chars) even with 10x10 boards.

Still holding high hopes for opt-pan san to at least grant 32x32 boards & 16x16x16 cubes.

**Comment by swaroopguggilam** [comment]
I see. 
Well there are URL shortening websites like tinyurl to shorten your URL before sharing in public forums.
Definitely, I think he might consider your issue, but might take some time. The only thing I can do is, I can increase the limits on my fork (Square limit is already increased to 40) when I release the update this weekend. So you can use the fork version in the meantime opt-pan address this issue in his version.

**Comment by swaroopg92** [comment]
I see.
Well there are URL shortening websites like tinyurl to shorten your URL before sharing in public forums.
Definitely, I think he might consider your issue, but might take some time. The only thing I can do is, I can increase the limits on my fork (Square limit is already increased to 40) when I release the update this weekend. So you can use the fork version in the meantime opt-pan address this issue in his version.

**Comment by opt-pan** [comment]
Thanks dujididoya. I'd like to check it often, but I apologize for the current situation where I have to update it once a month due to other work commitments.

The iso and hex aren't the upper limits of the software, so I've bumped it up to 16 and 12. square will also be bumped up to 32 to try it out, although it may cause some problems.

The size limit has been a concern from the beginning of the tool's creation. There are two issues there.
One is the length of the links that swaroop is discussing. The link has a huge amount of data, mainly to deal with deformed puzzles. Even with the current size, errors have been reported if a large number of objects are placed.
The second is the processing speed. On a huge board, there are thousands of objects to be drawn. This is more than a typical computer game. Therefore, the bigger the board, the slower it runs, and even placing a black square becomes difficult.
For these reasons, the current setting is the limit. 

I am trying to find a good solution to this problem.

**Comment by dujididoya** [comment]
Thanks so so much pals! It's now working perfectly fine for me! You know the feeling when you receive a new toy with almost everything you love to try and explore with, that's the excitement I feel now! \_(^o^)_/ 

While I'll still mostly use opt-pan san's version, I'll definitely check out swaroopg92's (& rjrudman's) fork to learn about the different features. Keep up the great work pals! ^_^

**Comment by swaroopg92** [comment]
There is no significant difference between opt-pan and rjrudman's fork. The rjrudman's fork was initially created for English translation. But thanks to opt-pan, he added that feature later in his fork itself for an automatic English translation.
My fork is definitely a bit different though as I am adding some other features which I need and some other's requests by users.
